# numpy slicing

In [2]:
import numpy as np

In [36]:
a = np.arange(100)

In [37]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
s = slice(2, 20, 2)

In [9]:
s

slice(2, 20, 2)

In [10]:
a[s]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
a[slice(1, 20, 1)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
a[2:7]

array([2, 3, 4, 5, 6])

In [13]:
a[1:30:3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [14]:
a[50:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
a[:30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
a = a.reshape(10, 10)

In [44]:
# (...)elipses
a[..., 3:6]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45],
       [53, 54, 55],
       [63, 64, 65],
       [73, 74, 75],
       [83, 84, 85],
       [93, 94, 95]])

In [45]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [48]:
a[2:4, 2:4] = 0

In [49]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31,  0,  0, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
a[np.isnan(a)]

array([], dtype=int32)

In [52]:
a[np.iscomplex(a)]

array([], dtype=int32)

In [53]:
# iteration
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
0
0
24
25
26
27
28
29
30
31
0
0
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [54]:
a.T

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12,  0,  0, 42, 52, 62, 72, 82, 92],
       [ 3, 13,  0,  0, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [56]:
for i in np.nditer(a, order='F'):
    print(i)

0
10
20
30
40
50
60
70
80
90
1
11
21
31
41
51
61
71
81
91
2
12
0
0
42
52
62
72
82
92
3
13
0
0
43
53
63
73
83
93
4
14
24
34
44
54
64
74
84
94
5
15
25
35
45
55
65
75
85
95
6
16
26
36
46
56
66
76
86
96
7
17
27
37
47
57
67
77
87
97
8
18
28
38
48
58
68
78
88
98
9
19
29
39
49
59
69
79
89
99


In [57]:
a[...]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31,  0,  0, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [58]:
a[...] = 10*a

In [59]:
a[...]

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210,   0,   0, 240, 250, 260, 270, 280, 290],
       [300, 310,   0,   0, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

# mathmatics operation

In [61]:
x = np.array([10, 30, 50, 20])

In [62]:
x

array([10, 30, 50, 20])

In [63]:
np.sin(x)

array([-0.54402111, -0.98803162, -0.26237485,  0.91294525])

In [64]:
np.cos(x)

array([-0.83907153,  0.15425145,  0.96496603,  0.40808206])

In [65]:
np.tan(x)

array([ 0.64836083, -6.4053312 , -0.27190061,  2.23716094])

In [66]:
np.pi

3.141592653589793

In [67]:
# radian value
sin = np.sin(a*np.pi/180)

In [68]:
sin

array([[ 0.00000000e+00,  1.73648178e-01,  3.42020143e-01,
         5.00000000e-01,  6.42787610e-01,  7.66044443e-01,
         8.66025404e-01,  9.39692621e-01,  9.84807753e-01,
         1.00000000e+00],
       [ 9.84807753e-01,  9.39692621e-01,  8.66025404e-01,
         7.66044443e-01,  6.42787610e-01,  5.00000000e-01,
         3.42020143e-01,  1.73648178e-01,  1.22464680e-16,
        -1.73648178e-01],
       [-3.42020143e-01, -5.00000000e-01,  0.00000000e+00,
         0.00000000e+00, -8.66025404e-01, -9.39692621e-01,
        -9.84807753e-01, -1.00000000e+00, -9.84807753e-01,
        -9.39692621e-01],
       [-8.66025404e-01, -7.66044443e-01,  0.00000000e+00,
         0.00000000e+00, -3.42020143e-01, -1.73648178e-01,
        -2.44929360e-16,  1.73648178e-01,  3.42020143e-01,
         5.00000000e-01],
       [ 6.42787610e-01,  7.66044443e-01,  8.66025404e-01,
         9.39692621e-01,  9.84807753e-01,  1.00000000e+00,
         9.84807753e-01,  9.39692621e-01,  8.66025404e-01,
         7.

In [71]:
# radian value of a
i = np.arcsin(sin)
i

array([[ 0.00000000e+00,  1.74532925e-01,  3.49065850e-01,
         5.23598776e-01,  6.98131701e-01,  8.72664626e-01,
         1.04719755e+00,  1.22173048e+00,  1.39626340e+00,
         1.57079633e+00],
       [ 1.39626340e+00,  1.22173048e+00,  1.04719755e+00,
         8.72664626e-01,  6.98131701e-01,  5.23598776e-01,
         3.49065850e-01,  1.74532925e-01,  1.22464680e-16,
        -1.74532925e-01],
       [-3.49065850e-01, -5.23598776e-01,  0.00000000e+00,
         0.00000000e+00, -1.04719755e+00, -1.22173048e+00,
        -1.39626340e+00, -1.57079633e+00, -1.39626340e+00,
        -1.22173048e+00],
       [-1.04719755e+00, -8.72664626e-01,  0.00000000e+00,
         0.00000000e+00, -3.49065850e-01, -1.74532925e-01,
        -2.44929360e-16,  1.74532925e-01,  3.49065850e-01,
         5.23598776e-01],
       [ 6.98131701e-01,  8.72664626e-01,  1.04719755e+00,
         1.22173048e+00,  1.39626340e+00,  1.57079633e+00,
         1.39626340e+00,  1.22173048e+00,  1.04719755e+00,
         8.

In [73]:
# degree
np.degrees(i)

array([[ 0.00000000e+00,  1.00000000e+01,  2.00000000e+01,
         3.00000000e+01,  4.00000000e+01,  5.00000000e+01,
         6.00000000e+01,  7.00000000e+01,  8.00000000e+01,
         9.00000000e+01],
       [ 8.00000000e+01,  7.00000000e+01,  6.00000000e+01,
         5.00000000e+01,  4.00000000e+01,  3.00000000e+01,
         2.00000000e+01,  1.00000000e+01,  7.01670930e-15,
        -1.00000000e+01],
       [-2.00000000e+01, -3.00000000e+01,  0.00000000e+00,
         0.00000000e+00, -6.00000000e+01, -7.00000000e+01,
        -8.00000000e+01, -9.00000000e+01, -8.00000000e+01,
        -7.00000000e+01],
       [-6.00000000e+01, -5.00000000e+01,  0.00000000e+00,
         0.00000000e+00, -2.00000000e+01, -1.00000000e+01,
        -1.40334186e-14,  1.00000000e+01,  2.00000000e+01,
         3.00000000e+01],
       [ 4.00000000e+01,  5.00000000e+01,  6.00000000e+01,
         7.00000000e+01,  8.00000000e+01,  9.00000000e+01,
         8.00000000e+01,  7.00000000e+01,  6.00000000e+01,
         5.

# statistics on numpy

In [74]:
a = np.array([[2, 34, 4], [45, 23, 13], [54, 76, 95]])

In [75]:
a

array([[ 2, 34,  4],
       [45, 23, 13],
       [54, 76, 95]])

In [76]:
np.amin(a)

2

In [77]:
a[2]

array([54, 76, 95])

In [78]:
np.amin(a[2])

54

In [79]:
np.amax(a)

95

In [80]:
np.amax(a[1])

45

In [81]:
# return min and maximum range
np.ptp(a)

93

In [85]:
np.ptp(a, axis=0)

array([52, 53, 91])

In [86]:
a

array([[ 2, 34,  4],
       [45, 23, 13],
       [54, 76, 95]])

In [90]:
np.percentile(a, 95, axis=0)

array([53.1, 71.8, 86.8])

In [100]:
a = np.array([[10, 50, 100], [20, 40, 110]])

In [97]:
np.percentile(a, 100, axis=0)

array([ 20.,  50., 110.])

1 - 100 = 25% -> 25, 50%-> 50, 100% -> 100

In [98]:
# min, mean, median, mode, max

In [99]:
a = np.arange(100)

In [103]:
b = np.array([100, 30, 25, 74, 72, 95, 110, 234, 32, 34, 45, 234, 543, 16, 23, 72, 652, 72, 34, 72, 64, 190])

In [104]:
b

array([100,  30,  25,  74,  72,  95, 110, 234,  32,  34,  45, 234, 543,
        16,  23,  72, 652,  72,  34,  72,  64, 190])

In [105]:
# min
np.amin(b)

16

In [106]:
# mean => avarage
np.mean(b)

128.3181818181818

In [107]:
# median
np.median(b)

72.0

In [108]:
np.average(b)

128.3181818181818

In [109]:
# standard deviation

In [ ]:
standard daviation formula = sqrt(mean(abs(b-b.mean))**2) # square root((mean(absolute(100-128)))^2) 
(100-128.3181818181818) = -28.3181818181818
-28**2 = _/-28**2 = -21


In [115]:
import math
math.sqrt(464)

21.540659228538015

In [112]:
np.std(b)

161.3052967522474

In [113]:
# variance
# formula = mean(abs(x-x.mean)**2)

In [114]:
np.var(b)

26019.398760330587