# Numpy => Numerical python

In [2]:
import numpy as np

In [4]:
# Array Declare
np.array([1, 2, 3, 4, 6, 8])

array([1, 2, 3, 4, 6, 8])

In [7]:
# one dimentional array
np.array(["234", 23, 43.45])

array(['234', '23', '43.45'], dtype='<U5')

In [15]:
arr_2d = np.array([[12, 4], [42, 53], [123, 4532]], ndmin=3)

In [17]:
type(arr_2d)

numpy.ndarray

In [18]:
arr_2d.ndim

3

In [20]:
arr_2d

array([[[  12,    4],
        [  42,   53],
        [ 123, 4532]]])

In [33]:
x = np.array([[12, 4], [42, 53], [123, 4532]], dtype='<i2')

In [34]:
x

array([[  12,    4],
       [  42,   53],
       [ 123, 4532]], dtype=int16)

In [50]:
y = np.array([(12, 4), (42, 53)], dtype=[('a', '<i2'), ('b', '<i8')])

In [51]:
y

array([(12,  4), (42, 53)], dtype=[('a', '<i2'), ('b', '<i8')])

In [56]:
type(y[0][1])

numpy.int64

In [58]:
# matrix
np.mat(np.array([[1,2], [3, 4]]))

matrix([[1, 2],
        [3, 4]])

In [60]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [61]:
# numpy asarray => convert the input to an array

In [62]:
l = [1, 2, 3]
l

[1, 2, 3]

In [63]:
type(l)

list

In [71]:
l = np.asarray(l)

In [65]:
type(np.asarray(l))

numpy.ndarray

In [67]:
np.asarray((1, 2, 3), dtype=np.int32)

array([1, 2, 3])

In [72]:
np.asarray(l) is l

True

In [73]:
l is l

True

In [74]:
#numpy from function

In [77]:
np.fromfunction(lambda i, j: i == j, (4, 4), dtype=int)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
[
    [1==1, 2==1, 3==1],
    [1==2, 2==2, 3==2],
    [1==3, 2==3, 3==3]
]

[[True, False, False], [False, True, False], [False, False, True]]

In [78]:
np.fromfunction(lambda i, j: i * j, (4, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [90]:
iterable = (x*x for x in range(10))
iterable

<generator object <genexpr> at 0x000002DDDA894EB0>

In [91]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [93]:
np.fromstring("10, 20, 30", sep=',', dtype=int)

array([10, 20, 30])

In [94]:
# numpy arrange function

In [96]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [97]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [102]:
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [106]:
#linspace
np.linspace(1, 5, 100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [107]:
# zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [108]:
#one 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
np.zeros(5, dtype=int)+5

array([5, 5, 5, 5, 5])

In [112]:
np.ones(10, dtype=int)+5

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [120]:
print(np.ones((5, 3, 8), dtype=int)+5)

[[[6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]]

 [[6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]
  [6 6 6 6 6 6 6 6]]]


In [121]:
#Random 

In [125]:
np.random.rand(2, 3)

array([[0.65107811, 0.19160156, 0.56764742],
       [0.78253414, 0.97614803, 0.59087094]])

In [123]:
np.random.randn(4, 3) # standerd normal

array([[-1.14241514,  1.79533118, -0.04587045],
       [ 0.48927087,  0.61761233, -0.00838553],
       [-1.26242036, -1.49271222, -0.67691302],
       [ 0.97743612,  0.16967859,  1.58936052]])

In [135]:
np.random.randint(1, 10)

2

In [137]:
np.random.randint(1, 10, 10)

array([3, 8, 6, 1, 3, 3, 2, 1, 6, 5])

In [139]:
np.random.randint(1, 10, (15, 15))

array([[4, 5, 4, 5, 8, 6, 2, 2, 7, 8, 6, 2, 3, 1, 9],
       [2, 7, 6, 7, 9, 9, 4, 4, 2, 4, 2, 6, 9, 5, 3],
       [5, 4, 3, 6, 6, 2, 4, 8, 4, 9, 1, 6, 5, 7, 8],
       [7, 6, 6, 4, 9, 6, 9, 6, 4, 1, 6, 6, 2, 5, 2],
       [3, 5, 2, 4, 1, 2, 4, 9, 1, 6, 4, 7, 8, 4, 3],
       [1, 9, 4, 6, 7, 7, 1, 8, 4, 9, 2, 4, 8, 6, 7],
       [7, 1, 2, 5, 7, 1, 6, 4, 1, 1, 6, 9, 5, 4, 6],
       [7, 8, 3, 6, 2, 1, 6, 6, 6, 6, 4, 1, 4, 8, 1],
       [4, 7, 8, 8, 7, 3, 7, 4, 6, 9, 3, 7, 8, 7, 3],
       [8, 7, 8, 4, 2, 7, 4, 3, 9, 4, 2, 5, 9, 6, 5],
       [5, 6, 9, 1, 4, 7, 7, 2, 4, 9, 7, 9, 5, 2, 4],
       [3, 5, 5, 7, 6, 6, 4, 5, 8, 7, 3, 1, 1, 5, 2],
       [3, 2, 8, 8, 2, 1, 1, 6, 4, 3, 8, 8, 7, 1, 3],
       [9, 2, 6, 7, 1, 4, 4, 9, 2, 4, 5, 2, 1, 7, 9],
       [2, 6, 9, 3, 2, 6, 7, 3, 1, 7, 2, 6, 7, 5, 6]])